services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount the source code for live reloading
      - .:/rails
      # Exclude these directories from volume mount for better performance
      - /rails/tmp
      - /rails/log
      - /rails/storage
      - /rails/node_modules
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    stdin_open: true
    tty: true
    command: >
      bash -c "
        bundle check || bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  bundle_cache: