services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app_home
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
